Budget\BudgetBundle\Entity\Fee:
    type: entity
    table: fee
    indexes:
        fk_fee_fees_category1_idx:
            columns:
                - fees_category_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        feeDate:
            type: date
            nullable: false
            column: fee_date
        amount:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
    manyToOne:
        feesCategory:
            targetEntity: FeesCategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fees_category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
