Budget\BudgetBundle\Entity\Spending:
    type: entity
    table: spending
    indexes:
        fk_spending_spending_category_idx:
            columns:
                - spending_category_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        spendingDate:
            type: date
            nullable: false
            column: spending_date
        amount:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
    manyToOne:
        spendingCategory:
            targetEntity: SpendingCategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                spending_category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
