goal_index:
    path:     /
    defaults: { _controller: "BudgetBundle:Goal:index" }
    methods:  GET

goal_show:
    path:     /{id}/show
    defaults: { _controller: "BudgetBundle:Goal:show" }
    methods:  GET

goal_new:
    path:     /new
    defaults: { _controller: "BudgetBundle:Goal:new" }
    methods:  [GET, POST]

goal_edit:
    path:     /{id}/edit
    defaults: { _controller: "BudgetBundle:Goal:edit" }
    methods:  [GET, POST]

goal_delete:
    path:     /{id}/delete
    defaults: { _controller: "BudgetBundle:Goal:delete" }
    methods:  DELETE
