resourcecategory_index:
    path:     /
    defaults: { _controller: "BudgetBundle:ResourceCategory:index" }
    methods:  GET

resourcecategory_show:
    path:     /{id}/show
    defaults: { _controller: "BudgetBundle:ResourceCategory:show" }
    methods:  GET

resourcecategory_new:
    path:     /new
    defaults: { _controller: "BudgetBundle:ResourceCategory:new" }
    methods:  [GET, POST]

resourcecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "BudgetBundle:ResourceCategory:edit" }
    methods:  [GET, POST]

resourcecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "BudgetBundle:ResourceCategory:delete" }
    methods:  DELETE
