spending_index:
    path:     /
    defaults: { _controller: "BudgetBundle:Spending:index" }
    methods:  GET

spending_show:
    path:     /{id}/show
    defaults: { _controller: "BudgetBundle:Spending:show" }
    methods:  GET

spending_new:
    path:     /new
    defaults: { _controller: "BudgetBundle:Spending:new" }
    methods:  [GET, POST]

spending_edit:
    path:     /{id}/edit
    defaults: { _controller: "BudgetBundle:Spending:edit" }
    methods:  [GET, POST]

spending_delete:
    path:     /{id}/delete
    defaults: { _controller: "BudgetBundle:Spending:delete" }
    methods:  DELETE
