spendingcategory_index:
    path:     /
    defaults: { _controller: "BudgetBundle:SpendingCategory:index" }
    methods:  GET

spendingcategory_show:
    path:     /{id}/show
    defaults: { _controller: "BudgetBundle:SpendingCategory:show" }
    methods:  GET

spendingcategory_new:
    path:     /new
    defaults: { _controller: "BudgetBundle:SpendingCategory:new" }
    methods:  [GET, POST]

spendingcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "BudgetBundle:SpendingCategory:edit" }
    methods:  [GET, POST]

spendingcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "BudgetBundle:SpendingCategory:delete" }
    methods:  DELETE
